package textdatamining;

import java.io.*;
import weka.core.*;
import weka.core.Instances;
import weka.classifiers.Evaluation;
import weka.classifiers.functions.MultilayerPerceptron;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;

/**
 *
 * @author spiros
 */

public class PerceptronFrame extends javax.swing.JFrame {

    String createModel = null;
    String path = null;
    Instances train;
    MultilayerPerceptron mlp = new MultilayerPerceptron();
    
    public PerceptronFrame() {
        Image img = Toolkit.getDefaultToolkit().createImage("Blueprint border.jpg");
        ImageIcon im = new ImageIcon();

        BufferedImage img1 = scaleImage(490, 600, "Blueprint border.jpg");

        im.setImage(img1);
        setContentPane(new JLabel(im));

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChooserFileARFF = new javax.swing.JFileChooser();
        ResultsDialog = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        CloseDialogButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TrainingButton = new javax.swing.JButton();
        OpenARFFfile = new javax.swing.JButton();
        ClassificationButton = new javax.swing.JButton();
        ClosePerceptronFrame = new javax.swing.JButton();
        HiddenLayersField = new javax.swing.JTextField();
        LearningRateField = new javax.swing.JTextField();
        MomentumField = new javax.swing.JTextField();
        TrainingTimeField = new javax.swing.JTextField();
        ValidationSetSizeFieldl = new javax.swing.JTextField();
        ValidationThresholdField = new javax.swing.JTextField();
        SeedField = new javax.swing.JTextField();

        ResultsDialog.setMinimumSize(new java.awt.Dimension(600, 550));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        CloseDialogButton.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        CloseDialogButton.setText("Close");
        CloseDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseDialogButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ResultsDialogLayout = new javax.swing.GroupLayout(ResultsDialog.getContentPane());
        ResultsDialog.getContentPane().setLayout(ResultsDialogLayout);
        ResultsDialogLayout.setHorizontalGroup(
            ResultsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultsDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ResultsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResultsDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CloseDialogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ResultsDialogLayout.setVerticalGroup(
            ResultsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResultsDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(CloseDialogButton)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Classification in Legal Texts");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("Create a MultiLayerPerceptron Model");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel3.setText("Hidden Layers :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Learning Rate :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Momentum :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Training Time :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("Validation Set Size :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setText("Validation Threshold :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel9.setText("Seed :");

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel10.setText("For training push the button :");

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel11.setText("For choose file push the button :");

        TrainingButton.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        TrainingButton.setText("Training");
        TrainingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainingButtonActionPerformed(evt);
            }
        });

        OpenARFFfile.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        OpenARFFfile.setText("Open");
        OpenARFFfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenARFFfileActionPerformed(evt);
            }
        });

        ClassificationButton.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        ClassificationButton.setText("Classification");
        ClassificationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassificationButtonActionPerformed(evt);
            }
        });

        ClosePerceptronFrame.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        ClosePerceptronFrame.setText("Close");
        ClosePerceptronFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClosePerceptronFrameActionPerformed(evt);
            }
        });

        HiddenLayersField.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        HiddenLayersField.setText("a");

        LearningRateField.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        LearningRateField.setText("0.3");

        MomentumField.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        MomentumField.setText("0.2");

        TrainingTimeField.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        TrainingTimeField.setText("500");

        ValidationSetSizeFieldl.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        ValidationSetSizeFieldl.setText("0");

        ValidationThresholdField.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        ValidationThresholdField.setText("20");

        SeedField.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        SeedField.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(38, 38, 38)
                        .addComponent(TrainingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClosePerceptronFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ClassificationButton, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jLabel1))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(OpenARFFfile, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SeedField)
                            .addComponent(ValidationThresholdField)
                            .addComponent(ValidationSetSizeFieldl)
                            .addComponent(TrainingTimeField)
                            .addComponent(MomentumField)
                            .addComponent(LearningRateField)
                            .addComponent(HiddenLayersField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(HiddenLayersField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(LearningRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(MomentumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TrainingTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ValidationSetSizeFieldl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ValidationThresholdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(SeedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(TrainingButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(OpenARFFfile)))
                    .addComponent(ClassificationButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ClosePerceptronFrame)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TrainingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainingButtonActionPerformed
        createModel = "-L " + LearningRateField.getText() + " -M " + MomentumField.getText() + " -N " + TrainingTimeField.getText()
                  + " -V " + ValidationSetSizeFieldl.getText() + " -S " + SeedField.getText() + " -E " + ValidationThresholdField.getText()
                  + " -H " + HiddenLayersField.getText();
        System.out.println(createModel);
        try {
            FileReader trainreader = new FileReader("C:\\Users\\spiros\\Documents\\TrainingSet.arff");
            train = new Instances(trainreader);
            train.setClassIndex(train.numAttributes() - 1);
            
            mlp.setOptions(Utils.splitOptions(createModel));
            mlp.buildClassifier(train);

            Evaluation eval = new Evaluation(train);
            eval.evaluateModel(mlp, train);

            jTextArea1.setText(eval.toSummaryString("\nTraining Results\n"
                                                    + "================\n", false) + "\n\n"
                      + eval.toClassDetailsString() + "\n\n" + eval.toMatrixString());

            ResultsDialog.setVisible(true);

            System.out.println(eval.toSummaryString("\nTRAIN Results\n======\n", false));
            System.out.println(eval.toClassDetailsString());
            System.out.println(eval.confusionMatrix());
            System.out.println(eval.toMatrixString());

            trainreader.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PerceptronFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PerceptronFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(PerceptronFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_TrainingButtonActionPerformed

    private void OpenARFFfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenARFFfileActionPerformed
        if (ChooserFileARFF.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            path = ChooserFileARFF.getSelectedFile().getAbsolutePath();
            System.out.println(path);
        }
    }//GEN-LAST:event_OpenARFFfileActionPerformed

    private void ClassificationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassificationButtonActionPerformed
        try {
            FileReader testreader = new FileReader(path);
            Instances test = new Instances(testreader);
            test.setClassIndex(test.numAttributes() - 1);

            Evaluation eval = new Evaluation(train);
            eval.evaluateModel(mlp, test);
            jTextArea1.setText(eval.toSummaryString("\nMultiLayer Perceptron - Classification Results\n"
                                                    + "==============================================\n", false) + "\n\n"
                      + eval.toClassDetailsString() + "\n\n" + eval.toMatrixString());

            ResultsDialog.setVisible(true);

            System.out.println(eval.toSummaryString("\nResults\n=======\n", false));
            System.out.println(eval.toClassDetailsString());
            System.out.println(eval.confusionMatrix());
            System.out.println(eval.toMatrixString());
            testreader.close();
        } catch (FileNotFoundException ex) {
        } catch (IOException ex) {
        } catch (Exception ex) {
            Logger.getLogger(PerceptronFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ClassificationButtonActionPerformed

    private void ClosePerceptronFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClosePerceptronFrameActionPerformed
        this.dispose();
    }//GEN-LAST:event_ClosePerceptronFrameActionPerformed

    private void CloseDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseDialogButtonActionPerformed
        ResultsDialog.setVisible(false);
    }//GEN-LAST:event_CloseDialogButtonActionPerformed

    public void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerceptronFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerceptronFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerceptronFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerceptronFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerceptronFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser ChooserFileARFF;
    private javax.swing.JButton ClassificationButton;
    private javax.swing.JButton CloseDialogButton;
    private javax.swing.JButton ClosePerceptronFrame;
    private javax.swing.JTextField HiddenLayersField;
    private javax.swing.JTextField LearningRateField;
    private javax.swing.JTextField MomentumField;
    private javax.swing.JButton OpenARFFfile;
    private javax.swing.JDialog ResultsDialog;
    private javax.swing.JTextField SeedField;
    private javax.swing.JButton TrainingButton;
    private javax.swing.JTextField TrainingTimeField;
    private javax.swing.JTextField ValidationSetSizeFieldl;
    private javax.swing.JTextField ValidationThresholdField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    BufferedImage scaleImage(int WIDTH, int HEIGHT, String filename) {
        BufferedImage bi = null;

        try {
            ImageIcon ii = new ImageIcon(filename); // path to image
            bi = new BufferedImage(WIDTH, HEIGHT, BufferedImage.TYPE_INT_RGB);
            Graphics2D g2d = (Graphics2D) bi.createGraphics();
            g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
            g2d.drawImage(ii.getImage(), 0, 0, WIDTH, HEIGHT, null);
        } catch (Exception e) {
            return null;
        }
        return bi;
    }

}
